FROM darthjee/production_dr_mario-base:0.1.0

USER root
WORKDIR /home/app/app
COPY ./ /home/app/app/
RUN chown app.app /home/app/app -R

USER app
RUN bundle install --clean --without development test

RUN bower install

USER root
CMD rails c
