version: '3'
services:
  dr_mario_mysql:
    image: mysql:5.7
    container_name: dr_mario_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: dr_mario
    ports:
      - 127.0.0.1:$DR_MARIO_MYSQL_PORT:3306

  #################### Base  ####################

  base: &base
    image: dr_mario
    volumes:
      - ./source:/home/app/app
    links:
      - dr_mario_mysql:mysql
    env_file: .env


  base_build:
    <<: *base
    build: .
    command: echo done

  #################### CONTAINERS ####################

  dr_mario_app:
    <<: *base
    container_name: dr_mario_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - DR_MARIO_MYSQL_PORT=3306

  dr_mario_tests:
    <<: *base
    container_name: dr_mario_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  dr_mario_root:
    <<: *base
    user: root
    container_name: dr_mario_root
    command: /bin/bash
    depends_on: [base_build]
  dr_mario_production:
    <<: *base
    container_name: dr_mario_production
    image: darthjee/production_dr_mario:latest
    environment:
      RAILS_ENV: production
