FROM darthjee/scripts:0.1.7 as scripts
######################################

FROM ruby:2.5.0 as base

RUN mkdir -p /home/app/app
WORKDIR /home/app/app

RUN gem install bundler
RUN curl -sL https://deb.nodesource.com/setup_10.x | /bin/bash
RUN apt-get update && apt-get install -y netcat nodejs

RUN npm install bower -g
######################################

FROM base as builder

COPY ./source/Gemfile* /home/app/app/

ENV HOME_DIR /home/app

COPY --from=scripts /home/scripts/builder/bundle_builder.sh /usr/local/sbin/bundle_builder.sh
RUN bundle_builder.sh --without development test

#######################
#FINAL IMAGE

FROM base

COPY --from=builder /home/app/bundle/gems/ /usr/local/bundle/gems/
COPY --from=builder /home/app/bundle/cache/ /usr/local/bundle/cache/
COPY --from=builder /home/app/bundle/specifications/ /usr/local/bundle/specifications/
COPY --from=builder /home/app/bundle/bin /usr/local/bundle/bin
COPY --from=builder /home/app/bundle/extensions /usr/local/bundle/extensions
