FROM darthjee/production_dr_mario-base:0.2.0

COPY --chown=app:app ./source/ /home/app/app/

RUN bundle install --clean --without development test; \
    bower install; \
    rm /home/app/app/tmp/pids/server.pid /home/app/app/public/assets/* -f; \
    RAILS_ENV=production rails assets:precompile
