version: 2
workflows:
  version: 2
  test:
    jobs:
      - test
      - build-and-release:
          requires: [test]
          filters:
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: darthjee/circleci_dr_mario-base:0.2.1
        environment:
          DR_MARIO_MYSQL_HOST: mysql
          DR_MARIO_MYSQL_PORT: 3306
          DR_MARIO_MYSQL_USER: dr_mario
          DR_MARIO_MYSQL_NAME: dr_mario
          DR_MARIO_MYSQL_PASSWORD: dr_mario
          DR_MARIO_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: dr_mario_test
          MYSQL_USER: dr_mario
          MYSQL_PASSWORD: dr_mario
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Bower Install
          command: bundle exec rake bower:install
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Make Build
          command: make PROJECT=production_dr_mario build
      - run:
          name: Build heroku image
          command: make build-heroku
      - run:
          name: Install Heroku
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: set heroku app
          command: heroku git:remote -a $HEROKU_APP_NAME
      - run:
          name: Heroku docker login
          command: heroku container:login
      - run:
          name: Release
          command: make release
