# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'bundler', '~> 1.16.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.2.4.1'

# Use pg as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '5.1.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '4.2.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'azeroth',      '>= 0.3.0'
gem 'bower-rails',  '~> 0.12.0'
gem 'newrelic_rpm', '~> 6.8.0.360'
gem 'nokogiri',     '1.10.7'
gem 'rake',         '13.0.1'
gem 'sinclair',     '1.5.2'
gem 'tarquinn',     '0.1.0'
gem 'turbolinks',   '5.2.1'

gem 'darthjee-core_ext', '>= 2.0.0'

group :development do
  # Access an interactive console on exception pages
  # or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your
  # application running in the background.
  # Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'factory_bot',        '5.1.1'
  gem 'pry',                '0.12.2'
  gem 'pry-nav',            '0.3.0'
  gem 'pry-rails',          '0.3.9'
  gem 'reek',               '5.4.0'
  gem 'rspec',              '3.9.0'
  gem 'rspec-core',         '3.9.1'
  gem 'rspec-rails',        '3.9.0'
  gem 'rspec-expectations', '3.9.0'
  gem 'rspec-mocks',        '3.9.1'
  gem 'rspec-support',      '3.9.2'
  gem 'rubocop',            '0.78.0'
  gem 'rubocop-rspec',      '1.37.1'
  gem 'rubycritic',         '4.3.1'
  gem 'shoulda-matchers',   '4.2.0'
  gem 'simplecov',          '0.17.1'
  gem 'yard',               '0.9.24'
  gem 'yardstick',          '0.9.9'
  gem 'zonebie',            '0.6.1'
end

group :development, :test do
  gem 'timecop', '0.9.1'

  gem 'rails-controller-testing', '1.0.4'
end

group :test do
  gem 'webmock', '3.5.1'

  gem 'database_cleaner'
  gem 'rspec-collection_matchers', '1.2.0'
end
